-- ============================================================
-- Cognitrix Mobile — push notifications + in-app inbox
--
-- Run once in: Supabase Dashboard > SQL Editor (same project as the website).
--
-- ADDITIVE ONLY: creates new tables/functions/triggers. No existing table,
-- column or policy is modified, so the website keeps working unchanged.
--
-- Because notifications are generated by database triggers, they fire no
-- matter where the action happened: a professor answering on the website
-- pushes to the student's phone, an approval on the phone shows up in the
-- inbox, and so on. Every trigger swallows its own errors, so a push failure
-- can never block the original insert/update.
-- ============================================================

create extension if not exists pg_net with schema extensions;


-- ------------------------------------------------------------
-- 1. Device push tokens
-- ------------------------------------------------------------
create table if not exists public.push_tokens (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  token       text not null unique,
  platform    text,
  updated_at  timestamp with time zone default now(),
  created_at  timestamp with time zone default now()
);

alter table public.push_tokens enable row level security;

drop policy if exists "push_tokens: users manage own" on public.push_tokens;
create policy "push_tokens: users manage own"
  on public.push_tokens for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists push_tokens_user_id_idx on public.push_tokens(user_id);

-- A phone can change hands (sign out / sign in as someone else). This reassigns
-- the token to the caller even if another user registered it before.
create or replace function public.register_push_token(p_token text, p_platform text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'not authenticated';
  end if;
  insert into push_tokens (user_id, token, platform, updated_at)
  values (auth.uid(), p_token, p_platform, now())
  on conflict (token) do update
    set user_id = excluded.user_id, platform = excluded.platform, updated_at = now();
end;
$$;

grant execute on function public.register_push_token(text, text) to authenticated;


-- ------------------------------------------------------------
-- 2. In-app notification inbox
-- ------------------------------------------------------------
create table if not exists public.notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  title       text not null,
  body        text,
  data        jsonb default '{}',
  read_at     timestamp with time zone,
  created_at  timestamp with time zone default now()
);

alter table public.notifications enable row level security;

-- Rows are only created by the security-definer functions below.
drop policy if exists "notifications: users read own" on public.notifications;
create policy "notifications: users read own"
  on public.notifications for select
  using (auth.uid() = user_id);

drop policy if exists "notifications: users update own" on public.notifications;
create policy "notifications: users update own"
  on public.notifications for update
  using (auth.uid() = user_id);

drop policy if exists "notifications: users delete own" on public.notifications;
create policy "notifications: users delete own"
  on public.notifications for delete
  using (auth.uid() = user_id);

create index if not exists notifications_user_created_idx on public.notifications(user_id, created_at desc);

-- Live updates for the app's bell badge / inbox.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'notifications') then
    alter publication supabase_realtime add table public.notifications;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'enrollments') then
    alter publication supabase_realtime add table public.enrollments;
  end if;
end $$;


-- ------------------------------------------------------------
-- 3. Core helpers
-- ------------------------------------------------------------

-- Creates an inbox row; the trigger in step 4 turns it into a push.
create or replace function public.notify_user(p_user uuid, p_title text, p_body text, p_data jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_user is null then return; end if;
  insert into notifications (user_id, title, body, data)
  values (p_user, p_title, left(p_body, 240), coalesce(p_data, '{}'::jsonb));
end;
$$;

-- Notifies every student actively enrolled in a course.
create or replace function public.notify_course_students(p_course uuid, p_title text, p_body text, p_data jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into notifications (user_id, title, body, data)
  select e.student_id, p_title, left(p_body, 240), coalesce(p_data, '{}'::jsonb)
  from enrollments e
  where e.course_id = p_course and e.status <> 'dropped';
end;
$$;

revoke execute on function public.notify_user(uuid, text, text, jsonb) from public, anon, authenticated;
revoke execute on function public.notify_course_students(uuid, text, text, jsonb) from public, anon, authenticated;


-- ------------------------------------------------------------
-- 4. Push delivery (Expo Push API via pg_net)
-- ------------------------------------------------------------
create or replace function public.send_expo_push()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  msgs jsonb;
  unread int;
begin
  select count(*) into unread from notifications where user_id = new.user_id and read_at is null;

  select jsonb_agg(jsonb_build_object(
    'to', t.token,
    'title', new.title,
    'body', coalesce(new.body, ''),
    'data', coalesce(new.data, '{}'::jsonb) || jsonb_build_object('notification_id', new.id),
    'sound', 'default',
    'badge', unread,
    'channelId', 'default',
    'priority', 'high'
  ))
  into msgs
  from push_tokens t
  where t.user_id = new.user_id;

  if msgs is not null then
    perform net.http_post(
      url := 'https://exp.host/--/api/v2/push/send',
      body := msgs,
      headers := '{"Content-Type": "application/json", "Accept": "application/json"}'::jsonb
    );
  end if;
  return new;
exception when others then
  raise warning '[send_expo_push] %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists on_notification_created_push on public.notifications;
create trigger on_notification_created_push
  after insert on public.notifications
  for each row execute function public.send_expo_push();


-- ------------------------------------------------------------
-- 5. Event triggers
-- ------------------------------------------------------------

-- 5a. Someone answered my question  → question author
create or replace function public.trg_notify_answer()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare q record;
begin
  select id, user_id, course_id, lecture_id into q from questions where id = new.question_id;
  if q.user_id is not null and q.user_id <> new.user_id then
    perform notify_user(
      q.user_id,
      coalesce(new.user_name, 'Your professor') || ' answered your question',
      new.text,
      jsonb_build_object('type', 'answer', 'question_id', q.id, 'course_id', q.course_id, 'lecture_id', q.lecture_id)
    );
  end if;
  return new;
exception when others then
  raise warning '[trg_notify_answer] %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists notify_on_answer on public.question_answers;
create trigger notify_on_answer
  after insert on public.question_answers
  for each row execute function public.trg_notify_answer();


-- 5b. Enrollment created (request approved) → student
create or replace function public.trg_notify_enrolled()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare c_title text;
begin
  -- Skip self-enrollment; only notify when someone else (professor/admin) enrolled the student.
  if auth.uid() is not null and auth.uid() = new.student_id then
    return new;
  end if;
  select title into c_title from courses where id = new.course_id;
  perform notify_user(
    new.student_id,
    'You''re enrolled! 🎉',
    'You now have access to ' || coalesce(c_title, 'your course') || '. Start learning now.',
    jsonb_build_object('type', 'enrolled', 'course_id', new.course_id)
  );
  return new;
exception when others then
  raise warning '[trg_notify_enrolled] %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists notify_on_enrolled on public.enrollments;
create trigger notify_on_enrolled
  after insert on public.enrollments
  for each row execute function public.trg_notify_enrolled();


-- 5c. Enrollment request created → professor; request rejected → student
create or replace function public.trg_notify_enrollment_request()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare c record; s_name text;
begin
  select id, title, professor_id into c from courses where id = new.course_id;

  if tg_op = 'INSERT' and new.status = 'pending' then
    select full_name into s_name from profiles where id = new.student_id;
    perform notify_user(
      c.professor_id,
      'New enrollment request',
      coalesce(s_name, 'A student') || ' wants to join ' || coalesce(c.title, 'your course'),
      jsonb_build_object('type', 'enroll_request', 'course_id', new.course_id, 'request_id', new.id)
    );
  elsif tg_op = 'UPDATE' and new.status = 'rejected' and old.status is distinct from 'rejected' then
    perform notify_user(
      new.student_id,
      'Enrollment request update',
      'Your request to join ' || coalesce(c.title, 'the course') || ' was not approved.',
      jsonb_build_object('type', 'enroll_rejected', 'course_id', new.course_id)
    );
  end if;
  return new;
exception when others then
  raise warning '[trg_notify_enrollment_request] %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists notify_on_enrollment_request on public.enrollment_requests;
create trigger notify_on_enrollment_request
  after insert or update of status on public.enrollment_requests
  for each row execute function public.trg_notify_enrollment_request();


-- 5d. New student question → course professor
create or replace function public.trg_notify_question()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare c record;
begin
  select id, title, professor_id into c from courses where id = new.course_id;
  if c.professor_id is not null and c.professor_id <> new.user_id then
    perform notify_user(
      c.professor_id,
      case when new.is_stuck_flag then '🚩 A student is stuck in ' else 'New question in ' end || coalesce(c.title, 'your course'),
      coalesce(new.user_name, 'A student') || ': ' || new.text,
      jsonb_build_object('type', 'question', 'course_id', new.course_id, 'lecture_id', new.lecture_id, 'question_id', new.id)
    );
  end if;
  return new;
exception when others then
  raise warning '[trg_notify_question] %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists notify_on_question on public.questions;
create trigger notify_on_question
  after insert on public.questions
  for each row execute function public.trg_notify_question();


-- 5e. New lecture published → enrolled students
create or replace function public.trg_notify_new_lecture()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare c_title text;
begin
  if coalesce(new.status, 'active') <> 'active' then return new; end if;
  select title into c_title from courses where id = new.course_id;
  perform notify_course_students(
    new.course_id,
    'New lecture in ' || coalesce(c_title, 'your course'),
    new.title,
    jsonb_build_object('type', 'new_lecture', 'course_id', new.course_id, 'lecture_id', new.id)
  );
  return new;
exception when others then
  raise warning '[trg_notify_new_lecture] %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists notify_on_new_lecture on public.lectures;
create trigger notify_on_new_lecture
  after insert on public.lectures
  for each row execute function public.trg_notify_new_lecture();


-- 5f. New quiz → enrolled students
create or replace function public.trg_notify_new_quiz()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare c_title text;
begin
  select title into c_title from courses where id = new.course_id;
  perform notify_course_students(
    new.course_id,
    '📝 New quiz available',
    new.title || ' — ' || coalesce(c_title, ''),
    jsonb_build_object('type', 'new_quiz', 'course_id', new.course_id, 'lecture_id', new.lecture_id, 'quiz_id', new.id)
  );
  return new;
exception when others then
  raise warning '[trg_notify_new_quiz] %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists notify_on_new_quiz on public.quizzes;
create trigger notify_on_new_quiz
  after insert on public.quizzes
  for each row execute function public.trg_notify_new_quiz();


-- ------------------------------------------------------------
-- To undo everything in this file:
--   drop trigger notify_on_new_quiz on quizzes;      drop trigger notify_on_new_lecture on lectures;
--   drop trigger notify_on_question on questions;    drop trigger notify_on_enrollment_request on enrollment_requests;
--   drop trigger notify_on_enrolled on enrollments;  drop trigger notify_on_answer on question_answers;
--   drop table notifications; drop table push_tokens;
-- ------------------------------------------------------------
